//users
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";

//authActions

//validation
export const VALIDATE_USER_IN_PROGRESS = "VALIDATE_USER_IN_PROGRESS";
export const VALIDATE_USER_SUCCESS = "VALIDATE_USER_SUCCESS";
export const VALIDATE_USER_FAILED = "VALIDATE_USER_FAILED";

//login
export const LOGIN_IN_PROGRESS = "LOGIN_IN_PROGRESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// logout
export const LOGOUT = "LOGOUT";

// SignUp
export const SIGNUP_IN_PROGRESS = "SIGNUPN_IN_PROGRESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// sent verification code
export const SENT_VERIFICATION_CODE_IN_PROGRESS = "SENT_VERIFICATION_CODE_IN_PROGRESS";
export const SENT_VERIFICATION_CODE_SUCCESS = "SENT_VERIFICATION_CODE_SUCCESS";
export const SENT_VERIFICATION_CODE_FAILED = "SENT_VERIFICATION_CODE_FAILED";

//update password
export const UPDATE_PASSWORD_IN_PROGRESS = "UPDATE_PASSWORD_IN_PROGRESS";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

//forgot password
export const FORGOT_PASSWORD_IN_PROGRESS = "FORGOT_PASSWORD_IN_PROGRESS";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED";

//get notification
export const GET_NOTIFICATION_IN_PROGRESS = "GET_NOTIFICATION_IN_PROGRESS";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILED = "GET_NOTIFICATION_FAILED";

//get current user
export const GET_CURRENT_USER_DATA_IN_PROGRESS = "GET_CURRENT_USER_DATA_IN_PROGRESS";
export const GET_CURRENT_USER_DATA_SUCCESS = "GET_CURRENT_USER_DATA_SUCCESS";
export const GET_CURRENT_USER_DATA_FAILED = "GET_CURRENT_USER_DATA_FAILED";

// get user values
export const GET_USER_VALUES_IN_PROGRESS = "GET_USER_VALUES_IN_PROGRESS";
export const GET_USER_VALUES_SUCCESS = "GET_USER_VALUES_SUCCESS";
export const GET_USER_VALUES_FAILED = "GET_USER_VALUES_FAILED";

//get total Graph data
export const GET_TOTAL_GRAPH_DATA_IN_PROGRESS = "GET_TOTAL_GRAPH_DATA_IN_PROGRESS";
export const GET_TOTAL_GRAPH_DATA_SUCCESS = "GET_TOTAL_GRAPH_DATA_SUCCESS";
export const GET_TOTAL_GRAPH_DATA_FAILED = "GET_TOTAL_GRAPH_DATA_FAILED";

//get return graph data
export const GET_RETURN_GRAPH_DATA_IN_PROGRESS = "GET_RETURN_GRAPH_DATA_IN_PROGRESS";
export const GET_RETURN_GRAPH_DATA_SUCCESS = "GET_RETURN_GRAPH_DATA_SUCCESS";
export const GET_RETURN_GRAPH_DATA_FAILED = "GET_RETURN_GRAPH_DATA_FAILED";

// get transaction data
export const GET_TRANSACTION_DATA_IN_PROGRESS = "GET_TRANSACTION_DATA_IN_PROGRESS";
export const GET_TRANSACTION_DATA_SUCCESS = "GET_TRANSACTION_DATA_SUCCESS";
export const GET_TRANSACTION_DATA_FAILED = "GET_TRANSACTION_DATA_SUCCESS";

// get User Accounts
export const GET_USER_ACCOUNTS_IN_PROGRESS = "GET_USER_ACCOUNTS_IN_PROGRESS";
export const GET_USER_ACCOUNTS_SUCCESS = "GET_USER_ACCOUNTS_SUCCESS";
export const GET_USER_ACCOUNTS_FAILED = "GET_USER_ACCOUNTS_FAILED";

// get account status
export const GET_ACCOUNT_STATUS_IN_PROGRESS = "GET_ACCOUNT_STATUS_IN_PROGRESS";
export const GET_ACCOUNT_STATUS_SUCCESS = "GET_ACCOUNT_STATUS_SUCCESS";
export const GET_ACCOUNT_STATUS_FAILED = "GET_ACCOUNT_STATUS_FAILED";

// upload status
export const UPLOAD_STATUS_IN_PROGRESS = "UPLOAD_STATUS_IN_PROGRESS";
export const UPLOAD_STATUS_SUCCESS = "UPLOAD_STATUS_SUCCESS";
export const UPLOAD_STATUS_FAILED = "UPLOAD_STATUS_FAILED";

//  get login user
export const GET_LOGIN_USER_IN_PROGRESS = "GET_LOGIN_USER_IN_PROGRESS";
export const GET_LOGIN_USER_SUCCESS = "GET_LOGIN_USER_SUCCESS";
export const GET_LOGIN_USER_FAILED = "GET_LOGIN_USER_FAILED";

//  get account list
export const GET_ACCOUNT_LIST_IN_PROGRESS = "GET_ACCOUNT_LIST_IN_PROGRESS";
export const GET_ACCOUNT_LIST_SUCCESS = "GET_ACCOUNT_LIST_SUCCESS";
export const GET_ACCOUNT_LIST_FAILED = "GET_ACCOUNT_LIST_FAILED";

// get admin user list
export const GET_USER_LIST_IN_PROGRESS = "GET_USER_LIST_IN_PROGRESS";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILED = "GET_USER_LIST_FAILED";

// account mapping
export const ACCOUNT_MAPPING_IN_PROGRESS = "ACCOUNT_MAPPING_IN_PROGRESS";
export const ACCOUNT_MAPPING_SUCCESS = "ACCOUNT_MAPPING_SUCCESS";
export const ACCOUNT_MAPPING_FAILED = "ACCOUNT_MAPPING_FAILED";
